# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.12.0
    hooks:
      - id: black
        args:
          - --skip-magic-trailing-comma
          - --target-version=py310
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        # profile and line-length to avoid clashes with black
        args: ["--profile=black", "--line-length=120"]

default_language_version:
  python: python3.10
