default_fetch_interval: 3600
default_relevance_threshold: 6.5
output_dir: "token_news"
default_rss_feeds:
  - https://cointelegraph.com/rss
  - https://www.coindesk.com/arc/outboundfeeds/rss/
  - https://decrypt.co/feed
  - https://www.dlnews.com/arc/outboundfeeds/rss/
tokens:
  - name: Liquid staked Ether 2.0
    symbol: stETH
    address:
      ethereum: "0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84"
    lookback_years: 2
    relevance_threshold: 8.0
    mandatory_phrases:
      - lido
      - staked eth
    additional_phrases:
      - defi
      - p2p.org
      - lido.fi
    rss_feeds:
      - https://blog.lido.fi/rss/
      - https://medium.com/feed/@lidofinance
